### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by Yeeheet** [dgudim/Scheduler#11]
Hey !

I've recently discovered your app and I absolutely love it ! 

There are two things that would be so cool to have :
- Ability to change events positions (center, top or down)
- dynamic accent color based on the wallpaper

Cheers !

**Comment by dgudim** [comment]
Thanks for being interested and for the suggestions! Glad you liked the app.

Just to clarify: you want to set background / border color to primary / secondary color of the wallpaper?

**Comment by dgudim** [comment]
> Ability to change events positions (center, top or down)

Implemented :)
Please clarify on the dynamic colors @Yeeheet

**Comment by Yeeheet** [comment]
> > Ability to change events positions (center, top or down)
> 
> Implemented :)
> Please clarify on the dynamic colors @Yeeheet 

Nice !

By dynamic colors I mean that events colors would be based off the wallpaper dominant color.

**Comment by dgudim** [comment]
A similar functionality is already there, "blend with background" will take an average color from the piece of wallpaper right under the event (just set it to anything above 0), this already looks good, I don't think mixing with primary color would be any better.
@Yeeheet

**Comment by Yeeheet** [comment]
> A similar functionality is already there, "blend with background" will take an average color from the piece of wallpaper right under the event (just set it to anything above 0), this already looks good, I don't think mixing with primary color would be any better.
> @Yeeheet 

Oh indeed just seen it :) 
Thanks for implementing the feature requested !

**Comment by dgudim** [comment]
Released: https://github.com/dgudim/Scheduler/releases/tag/v0.5.7
