### ISSUE TITLE
Starting Day of Week on left side 

### ISSUE THREAD

**Issue by VulcanElf** [dgudim/Scheduler#12]
If user had ability to change "starting" day of week to Sunday, so Sundays would show on the furthest Left Side Column, that would be extremely helpful.

**Comment by dgudim** [comment]
Thanks for the suggestion, this will be implemented in the next release

**Comment by dgudim** [comment]
Implemented in https://github.com/dgudim/Scheduler/releases/tag/v0.5.7

**Comment by VulcanElf** [comment]
Thank you! The update makes it much better!
