### ISSUE TITLE
Order of items & times

### ISSUE THREAD

**Issue by VulcanElf** [dgudim/Scheduler#13]
I would like to request the scheduled items on the lock screen to be able to be ordered in chronological order (ie: Current schedules on top, upcoming listed underneath the current, and past events either on the bottom OR very top).

Also, the ability to add times for each scheduled task would be very helpful as well.

**Comment by dgudim** [comment]
Thanks for the feature request and for the donation, sorting is already in my todo list, so expect it in a few days. :)

About times though, so you would like the events to behave like normal calendar events? 
Because calendar events and todo items are kinda different things, i can add an ability to add the time, but making it respect the "hide events by time" switch would not be so easy, and besides, someone will probably aks for an ability to make the events recurring, which would just make them calendar events.

**Comment by VulcanElf** [comment]
I use ProtonCalendar, so if that's able to sync with Scheduler, then adding times wouldn't be needed. Maybe even other calendars to sync with Scheduler would be helpful for users.

**Comment by dgudim** [comment]
Scheduler already has functionality to sync with system calendars, it's just that [proton does not seem to register itself as a system calendar](https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/42344065-sync-with-other-calendars-office365-google). There is [one option](https://proton.me/support/share-calendar) (Only if you use proton premium). My google and local calendars sync perfectly fine.

**Comment by dgudim** [comment]
<h2> What do you think? </h2> @VulcanElf 

<br>

<img src="https://user-images.githubusercontent.com/34401005/211003436-f700fa76-7e96-41be-8c72-3c45f95de577.jpg" width=50%>

**Comment by VulcanElf** [comment]
Looks good!
I also was able to create a shareable link via ProtonCalendar, but etesync customer service has not responded in several days with any assistance.

Is there a way to share the ProtonCalendar link thru the app intself?

-------- Original Message --------

**Comment by dgudim** [comment]
Syncing with a calendar from a link would require writing my own sync adapter, so no, you can't do that. But you can import this calendar into your google calendar, or you can try DAVx5 @VulcanElf

**Comment by dgudim** [comment]
Can you send me a link to some proton calendar (any calendar with at least one event)? I want to test something @VulcanElf

**Comment by dgudim** [comment]
Sorting implemented in <a href="https://github.com/dgudim/Scheduler/releases/tag/v0.5.8"><b style="font-size:75">0.5.8</b></a>

**Comment by dgudim** [comment]
Did you manage to solve the issue, can i close it now?

**Comment by VulcanElf** [comment]
Yes I did. I just downloaded the ICS file from protonmail, and imported to etesync.

Unfortunately Ill have to manually do this everymonth for my new schedule

-------- Original Message --------

**Comment by dgudim** [comment]
Good that it's solved. But can you send me a link to some proton calendar (any calendar with at least one event)? I want to test how hard would it be to implement syncing. (Google calendar links won't work so that's why I am asking)

**Comment by dgudim** [comment]
Can you? @VulcanElf

**Comment by dgudim** [comment]
I am going to close this as stale in a few day, please give me the link if you want me to try adding the syncing functionality @VulcanElf

**Comment by dgudim** [comment]
I am closing this, feel free to reopen if you change your mind
