### ISSUE TITLE
wrong versioning in latest release

### ISSUE THREAD

**Issue by IzzySoft** [dgudim/Scheduler#14]
the last 2 releases have the very same `versionName` and `versionCode`. Could you please make sure at least `versionCode` is unique to each release? Hard to tell them apart otherwise (Android considers them to be the very same versions/releases if `versionCode` is identical). Thanks in advance!

**Comment by dgudim** [comment]
The version code is the same because I didn't want to increment version number 0.5.8 to 0.5.9. I am aware that android treats them as the same version. Version name is different, so it's fine, the user will just be able to downgrade.

**Comment by dgudim** [comment]
I have one issue with the changelog tho, several days ago it turned into this
![Screenshot_20230112_220716_F-Droid](https://user-images.githubusercontent.com/34401005/212174154-98192d28-df8e-496e-b8de-b4a5b2bdae01.jpg)

**Comment by IzzySoft** [comment]
> Version name is different, so it's fine, the user will just be able to downgrade.

`versionCode` is the same, so the user won't even receive an update information – as Android (and thus also the F-Droid client) treats the new APK as being the same as the already installed one.

That with the changelog is funny: did it really happen just "several days ago"? The last code change to the corresponding class was in mid-December – and the first broken changelog indeed was 504 from 2022-12-21, so I have an idea what caused the issue… yupp, fixed (reflected with the next sync tomorrow) – thanks for bringing this up!

**Comment by dgudim** [comment]
> So the user won't even receive an update information 

Didn't think about that, will bump the version then

<br>

> did it really happen just "several days ago"

That's when I noticed it

<br>

> yupp, fixed

Thanks

**Comment by IzzySoft** [comment]
> Didn't think about that

Easily overlooked. You can of course always `adb install -r *.apk`, so it should be fine – but a) not getting an update notification you don't know you should, and b) thinking it's the same version, the F-Droid client used might not offer you an "install" button to re-install :wink: So thanks for taking care!

> That's when I noticed it

Yes, I reasoned that – and good you did! I've manually checked the updates of the last 14d (100+) and fixed a bunch of "broken" changelogs. With the side effect of discovering other things (like full changelogs since the first released put there for each `versionCode`, resulting in multiple 40+ kB files which would be truncated at 500 char in the middle of "something", or always the same file just saying "see {link}" :see_no_evil:) – so thanks to this mishap, several other improvements were made :zany_face:

Feel free to close this issue once the bump has been implemented – and thanks again!

**Comment by dgudim** [comment]
Bump done )

**Comment by IzzySoft** [comment]
Then let's look forward to my updater running in about 1.5h and whether it complains again (should not if all went fine, and I expect it went fine – if not, I'll know at about 7 pm UTC).

**Comment by IzzySoft** [comment]
As expected: Update was pulled, Updater did not complain – full success! :star_struck: Thanks!
