### ISSUE TITLE
Wallpaper not updating and local events dissapearing [COCKROACH]

### ISSUE THREAD

**Issue by PeuDenPau** [dgudim/Scheduler#15]
**Describe the bug**
Love the app and the concept of it, but i can't get it to work. First time worked, but after that if failed to update te wallpaper and the events keeps diseapering. Can paste the logs:

At install:
_23/01 08:36  [INFO]: Root dir: /storage/emulated/0/Android/data/prototype.xd.scheduler/files
23/01 08:37  [INFO]: Root dir: /storage/emulated/0/Android/data/prototype.xd.scheduler/files
23/01 08:37  [INFO]: No groups file (java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/groupData.old)
23/01 08:37  [INFO]: Received ping (initial)
23/01 08:37  [INFO]: restart job scheduled
23/01 08:37  [INFO]: got display metrics: DisplayMetrics{density=2.34375, width=1080, height=2400, scaledDensity=2.34375, xdpi=403.411, ydpi=401.052}
23/01 08:37  [INFO]: Loaded 10 calendars
23/01 08:37  [INFO]: No todo list: (java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old)
23/01 08:37  [INFO]: Read calendar entries: 19
23/01 08:37  [INFO]: TodoEntryManager cold start complete in 114ms, loaded 19 entries
23/01 08:38  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 08:38  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 08:38  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 08:38  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 08:38  [INFO]: Sent ping (on - off receiver)
23/01 08:38  [INFO]: Receiver state: android.intent.action.SCREEN_OFF
23/01 08:38  [INFO]: Received general ping_

Each change of wallpaper event throw the same errors:

_23/01 08:38  [INFO]:  ------------ Setting wallpaper ------------ 
23/01 08:38  [INFO]: Receiver state: android.intent.action.SCREEN_ON
23/01 08:38  [INFO]: No groups file (java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/groupData.old)
23/01 08:38  [INFO]: Loaded 10 calendars
23/01 08:38  [INFO]: No todo list: (java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old)
23/01 08:38  [INFO]: Read calendar entries: 2
23/01 08:38  [INFO]: Processed wallpaper in 294ms
23/01 08:38  [INFO]:  ------------ Set wallpaper in 0.174s ------------ 
23/01 08:38  [INFO]: Cleaning up TodoEntryManager (20 entries, 1 groups)
23/01 08:38  [INFO]: TodoEntryManager destroyed
23/01 08:38  [INFO]: Async writer stopped
23/01 08:38  [INFO]: No groups file (java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/groupData.old)
23/01 08:38  [INFO]: Root dir: /storage/emulated/0/Android/data/prototype.xd.scheduler/files
23/01 08:38  [INFO]: Loaded 10 calendars
23/01 08:38  [INFO]: No todo list: (java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old)
23/01 08:38  [INFO]: Read calendar entries: 19
23/01 08:38  [INFO]: TodoEntryManager cold start complete in 56ms, loaded 19 entries
23/01 08:38  [INFO]: Received general ping_

More errors after tinkering a little bit with it:

_23/01 13:34  [INFO]:  ------------ Setting wallpaper ------------ 
23/01 13:34  [INFO]: No groups file (java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/groupData.old)
23/01 13:34  [INFO]: Loaded 10 calendars
23/01 13:34  [INFO]: No todo list: (java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old)
23/01 13:34  [INFO]: Read calendar entries: 2
23/01 13:34  [INFO]: Processed wallpaper in 114ms
23/01 13:34  [INFO]:  ------------ Set wallpaper in 0.169s ------------ 
23/01 13:35  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 13:35  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 13:36  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 13:36  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 13:36  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 13:36  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 13:36  [ERROR]: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/groupData -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/groupData.old
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:396)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at prototype.xd.scheduler.utilities.f.o(Unknown Source:59)
	at prototype.xd.scheduler.utilities.TodoEntryManager$b.run(Unknown Source:22)_

_23/01 13:36  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 13:36  [ERROR]: Missing permission, failed saving todo list: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries -> /storage/emulated/0/Android/data/prototype.xd.scheduler/files/entries.old
23/01 13:36  [INFO]: Sent ping (on - off receiver)
23/01 13:36  [INFO]: Receiver state: android.intent.action.SCREEN_OFF
23/01 13:36  [INFO]: Received general ping_

No error is shown in app and it doesn't crashes. Would love a fix for it. Tell me if i could help anyway. 

Thank you!

 - Device: Nothing Phone (1)
 - UI shell version: Stock (non rooted)
 - OS: Android 12
 - App version: 0.6.0

**Comment by dgudim** [comment]
Did the problem appear after updating the app? Try clearing the data of the app, setting your lockscreen wallpaper from system settings and starting the app again, if that doesn't fix the problem let me know

**Comment by dgudim** [comment]
Nevermind, i was able to reproduce the bug, please try the version attached below and see if it's resolved
[app-release](https://github.com/dgudim/Scheduler/files/10488032/app-release.zip)

**Comment by PeuDenPau** [comment]
It looks fixed! Thank you very much.

**Comment by dgudim** [comment]
And thanks you, bug hunting is always appreciated. Fell free to reopen it/open a new one if you find more bugs.
