### ISSUE TITLE
[COCKROACH] Scheduler Won't Uninstall

### ISSUE THREAD

**Issue by shanejabo** [dgudim/Scheduler#19]
**Describe the bug**
When I try to uninstall the app it instantly crashes the package manager, and remains installed. I installed it off of the F-Droid repo.

**To Reproduce**
1. Go to 'App Info'
2. Click on 'Uninstall'
4. Crashes

OR 

1. Go to 'App Drawer"
2. Hold the 'Scheduler Icon'
3. Click on 'Uninstall'
6. After multiple attempts: 'Package installer keeps stopping."

**Expected behavior**
Scheduler uninstalling with no issues.

**Screenshots**
![1000029657](https://github.com/dgudim/Scheduler/assets/132114907/283bba2c-c5ad-40f4-bbb4-e216c90f15f2)

**The following information**
 - Device: [Samsung Z Flip3 5G]
 - UI shell version (One UI 5.1)
 - OS: [Android 13]
 - App version [0.6.3.release]

**Additional context**
I don't want to factory reset my phone 😮‍💨.

**Comment by dgudim** [comment]
Omg, I don't think it's an issue with my app, have you tried rebooting? I also have OneUI 5.1 and it works fine

**Comment by dgudim** [comment]
Did it solve itself?

**Comment by shanejabo** [comment]
Thank you! I had to enable 'Usage data access' for 'Package Installer.' It was hidden inside of 'Special access' in App permissions. 🤑
