### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by UmerCodez** [dgudim/Scheduler#4]
Hi, 
Please update README and specify that this app runs on Android 8 and above.  
I was getting installation error on Android 7 not knowing that minimum required OS is Android 8

**Comment by dgudim** [comment]
Hmm, sure

**Comment by dgudim** [comment]
Added requirements, thanks for suggestion 
[Commit 133e8e8325cacfb00b00dc5bacca03dc47c5c80e](https://github.com/dgudim/Scheduler/commit/133e8e8325cacfb00b00dc5bacca03dc47c5c80e)
