### ISSUE TITLE
[FEATURE REQUEST] Ability for an event that last more than one day

### ISSUE THREAD

**Issue by Terkyz** [dgudim/Scheduler#5]
**Is your feature request related to a problem? Please describe.**
Yes, maybe it's already in development or I just found a way to do it, but I don't see how I can add an event that takes several days, [like in Simple Calendar](https://i.imgur.com/jzr4OtL.jpg) (or any other calendar).  

**Describe the solution you'd like**
When adding or editing an event, have an option for "Start date" and "End date".

**Describe alternatives you've considered**

**Additional context**

**Comment by dgudim** [comment]
Those events are not supposed to behave like normal calendar events (because they are not calendar events) But sure, making an option for them to span multiple days shouldn't be too hard, I'll think about it

**Comment by dgudim** [comment]
Added in 0.5.4
