### ISSUE TITLE
[COCKROACH] No way to delete global events

### ISSUE THREAD

**Issue by Terkyz** [dgudim/Scheduler#6]
**Describe the bug**
[When adding an event to the global list](https://i.imgur.com/Vu83S5O.jpg), it does [appear](https://i.imgur.com/EE7DesP.jpg) on the lockscreen [but not in the Scheduler calendar](https://i.imgur.com/j4aRDts.jpg) so I have no way to delete it and I had to deactivate the option "Show global events on lockscreen" because they just stay there without me being able to do anything.

**To Reproduce**
Create a global event and look at the Schenduler calendar, no event appears. 

**Expected behavior**
The newly created event appears in my calendar and allows me to delete it.

**Screenshots**

**The following information**
 - Device: [Samsung A10]
 - UI shell version (idk
 - OS: [e.g. Android 11]
 - App version [e.g. 0.5.3]

**Additional context**

**Comment by dgudim** [comment]
Thanks for reporting the bug. I tested it and yes, the global events are indeed broken, i will fix that in the next release.

**Comment by dgudim** [comment]
And by the way, can you tell me your timezone and locale info? Because i noticed that the selected date is wrong (You selected 24th and it says 23rd) I need to investigate that

**Comment by Terkyz** [comment]
GMT-06:00 Central Standard Time, 09:58AM, December 15th

It's that?

**Comment by dgudim** [comment]
Yeah, thanks, and also your language please

**Comment by Terkyz** [comment]
Spanish

**Comment by dgudim** [comment]
Fixed in 0.5.4
