### ISSUE TITLE
[FEATURE REQUEST] Ability to "Show all events on lockscreen".

### ISSUE THREAD

**Issue by Terkyz** [dgudim/Scheduler#7]
**Is your feature request related to a problem? Please describe.**
No. But there is a button that does this function with global events, it would be great the same with any event, so I don't need to manually add each event to the lockscreen.

**Describe the solution you'd like**
An option to "Show all events on the lockscreen" or an option like this per calendar

**Describe alternatives you've considered**

**Additional context**

**Comment by dgudim** [comment]
So you want normal events to behave like global ones? I am not getting your point, displaying all events will be a mess. I can add an optional toggle to hide the "(Global)" part on the lock screen tho

**Comment by Terkyz** [comment]
I probably explained myself wrong though, my point is that I think that manually adding each event to the lockscreen is a bit tedious, mainly because in my case I want all the events I am going to add to appear there, though I think this bug can be closed because once the global events are working fine, I will simply create my events as global events

**Comment by dgudim** [comment]
Yeah, would you still like me to add that optional toggle?

**Comment by Terkyz** [comment]
Sure

**Comment by dgudim** [comment]
Added in 0.5.4
