### ISSUE TITLE
[COCKROACH] Strange behavior using CALDav and Etesync

### ISSUE THREAD

**Issue by Terkyz** [dgudim/Scheduler#8]
**Describe the bug**
To experiment with the app I installed EteSync, which is basically a CALDav service but out-of-the-box, [in Android just installing the app works perfectly and synchronizes the events with the client/web page](https://i.imgur.com/qWocXo9.jpg) as if it were another calendar on the device and in fact [Scheduler recognizes it](https://i.imgur.com/VX3XIyR.jpg) in the "System calendar integration" tab, the problem is that [the events are not displayed on the lockscreen](https://i.imgur.com/hOFUCDi.jpg), [but they are displayed on the calendar tab on Scheduler](https://i.imgur.com/I6ELDKP.jpg)

**To Reproduce**
Create a calendar in EteSync, synchronize with Scheduler, create an event in Etesync or directly in the system calendar

**Expected behavior**
Events are displayed correctly on the lockscreen

**Screenshots**
The screenshot where my lockscreen appears and a test called ẗest¨, that is a past event that I create in Etesync, which for some reason stayed there

**The following information**
 - Device: Samsung A10
 - UI shell version IDK
 - OS: Android 11
 - App version 0.5.3

**Additional context**

**Comment by dgudim** [comment]
Hmmm, needs investigation, thanks again for bug hunting, 3 days and already found 3 bugs, wow.

**Comment by dgudim** [comment]
I tried reproducing the bug and could not, i am not closing this issue yet, in a few days I'll make a new release, we will see if the issue persists

**Comment by Terkyz** [comment]
I found the problem, basically by default Schenduler has a default value of 0 in "Show events in x day/days", if this is set to 0 it does not show upcoming events, only events of the same day

**Comment by dgudim** [comment]
Ah, yes, it does, closing as resolved then
