### ISSUE TITLE
[COCKROACH] Weird app behavior on first start

### ISSUE THREAD

**Issue by CodeCubeNeo** [dgudim/Scheduler#9]
I cant do anything. the app isnt responsive when i swipe from bottom up to read the notes. Here is a video that shows that. I am writing from my phone so sorry for the inarticulate writing.

https://user-images.githubusercontent.com/61159092/208998147-c6d2619d-6eb2-4ea8-9d15-f32fca70fa5b.mp4

**Comment by dgudim** [comment]
Oh, I know why, the screen is not long enough, sorry for the inconvenience, will fix tomorrow

**Comment by dgudim** [comment]
You can reduce system font size, that should help for now

**Comment by CodeCubeNeo** [comment]
That was faast. Awesome!

**Comment by dgudim** [comment]
Should be fixed in 0.5.5
